version: '3'
services:
  client-proxy:
    image: client-proxy 
    environment:
    volumes:
      - ./demo/log/express.log.d:/app/log
      - ./shop_data:/var/lib/mysql
    networks:
      - shop_network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - auth_network
      - shop_network

  auth-database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./auth_init:/docker-entrypoint-initdb.d
      - ./auth_data:/var/lib/mysql
    networks:
      - auth_network
    ports:
      - 3307:3306

  auth-service:
    image: auth-service-image
    environment:
      - DATABASE_URL=auth-database
      - BLOCKCHAIN_URL=blockchain
    networks:
      - auth_network
    ports:
      - 5000:5000

  owner-service:
    image: owner-service-image
    environment:
      - DATABASE_URL=shop-database
      - SPARKAPP_URL=sparkapp
      - OWNER_PRIVATE_KEY=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    networks:
      - shop_network
    ports:
      - 5001:5000

  buyer-service:
    image: buyer-service-image
    environment:
      - DATABASE_URL=shop-database
      - BLOCKCHAIN_URL=blockchain
      - OWNER_PRIVATE_KEY=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    networks:
      - shop_network
    ports:
      - 5002:5000

  courier-service:
    image: courier-service-image
    environment:
      - DATABASE_URL=shop-database
      - BLOCKCHAIN_URL=blockchain
      - OWNER_PRIVATE_KEY=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    networks:
      - shop_network
    ports:
      - 5003:5000

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shop_network
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shop_network
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shop_network
  sparkapp:
    image: sparkapp
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkapp
      - DATABASE_IP=shop-database
    ports:
      - 5004:5000
    networks:
      - shop_network
  blockchain:
    image: trufflesuite/ganache-cli:latest
    command: --account="0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef,1000000000000000000000000000000000000000"
    ports:
      - 8545:8545
    networks:
      - shop_network
networks:
  auth_network:
  shop_network:
